(function(){
  const replacements=[
    ['Unisex Half-Crew Throwback Sock','Unisex Half-Crew Throwback Socken'],['20 colours','20 Farben'],
    ['BUILT FOR STRENGTH','FÜR STÄRKE GEMACHT'],['Made for every shake and hold — movement that feels like you.','Für jede Bewegung gemacht — Activewear, die sich nach dir anfühlt.'],['SHOP NOW','JETZT SHOPPEN'],
    ['NEW RELEASES','NEUHEITEN'],['Explore our latest products','Entdecke unsere neuesten Produkte'],['Shop all','Alle ansehen'],['OWN YOUR JOURNEY','GEH DEINEN EIGENEN WEG'],['Stories of Strength Capsule','Stories of Strength Kollektion'],['BUILD YOUR WISHLIST','WUNSCHLISTE ERSTELLEN'],
    ['BEST SELLERS','BESTSELLER'],['Your favourites, right here','Deine Favoriten auf einen Blick'],['SHOP BY CATEGORY','NACH KATEGORIE SHOPPEN'],['Find your movement essential','Finde deine Activewear-Essentials'],['JUST FOR YOU','FÜR DICH'],['Our top recommendations','Unsere Empfehlungen'],
    ['products','Produkte'],['Search this collection','Kollektion durchsuchen'],['Featured','Empfohlen'],['Price: low to high','Preis: aufsteigend'],['Price: high to low','Preis: absteigend'],['All categories','Alle Kategorien'],
    ['In stock — ready to ship','Auf Lager — versandbereit'],['In stock — all sizes available','Auf Lager — alle Grössen verfügbar'],['SELECT FIT','PASSFORM WÄHLEN'],['SELECT COLOUR','FARBE WÄHLEN'],['SELECT US SIZE (UK SIZE)','GRÖSSE WÄHLEN'],['UK SIZE GUIDE','EU-GRÖSSENTABELLE'],
    ['ADD TO BAG','IN DEN WARENKORB'],['ADD THE COMPLETE SET TO BAG','KOMPLETTES SET IN DEN WARENKORB'],['5,000+ happy customers','Mehr als 5.000 zufriedene Kundinnen'],['Read reviews','Bewertungen lesen'],['Read Airbrush Set reviews','Airbrush Set Bewertungen lesen'],
    ['FREE 48H SHIPPING','KOSTENLOSE 48H-LIEFERUNG'],['On every UK order','Für jede Schweizer Bestellung'],['60-DAY RETURNS','60 TAGE RÜCKGABE'],['Free, no questions asked','Kostenlos und unkompliziert'],['SECURE PAYMENT','SICHERE ZAHLUNG'],['SSL encrypted checkout','SSL-verschlüsselte Zahlung'],
    ['YOUR COMPLIMENTARY GIFT','DEIN GRATISGESCHENK'],['FREE GIFT WITH YOUR SET','GRATISGESCHENK ZU DEINEM SET'],['Automatically included in your parcel — no code needed.','Automatisch in deinem Paket — kein Code erforderlich.'],['FREE','GRATIS'],
    ['COMPLETE 2-PIECE SET','KOMPLETTES 2-TEILIGES SET'],['Sports bra + matching bottom','Sport-BH + passende Hose'],['1. CHOOSE YOUR TOP SIZE','1. OBERTEIL-GRÖSSE WÄHLEN'],['2. CHOOSE YOUR BOTTOM SIZE','2. HOSEN-GRÖSSE WÄHLEN'],
    ['Excellent','Ausgezeichnet'],['Based on 649 product reviews','Basierend auf 649 Produktbewertungen'],['Loved by 5,000+ customers','Beliebt bei mehr als 5.000 Kundinnen'],['Verified customer','Verifizierte Kundin'],['out of 5','von 5'],['Close reviews','Bewertungen schliessen'],['Customer reviews','Kundenbewertungen'],
    ['Choose your fit','Wähle deine Passform'],['Fit and features','Passform und Details'],['Free 48-hour shipping','Kostenlose Lieferung innerhalb von 48 Stunden'],['Free 60-day returns','60 Tage kostenlose Rückgabe'],['60-day guarantee','60 Tage Garantie'],['Product details','Produktdetails'],['What is included?','Was ist enthalten?'],['Fit & fabric','Passform und Material'],
    ['YOU MAY ALSO LIKE','DAS KÖNNTE DIR AUCH GEFALLEN'],['Complete the look','Vervollständige den Look'],['COMPLETE THE LOOK','LOOK VERVOLLSTÄNDIGEN'],['More movement essentials','Weitere Activewear-Essentials'],
    ['Everyday sculpt','Formend für jeden Tag'],['Made to move','Für Bewegung gemacht'],['Your strongest self','Deine stärkste Version'],['Confidence in motion','Selbstvertrauen in Bewegung'],['Play video','Video abspielen'],['Previous videos','Vorherige Videos'],['Next videos','Nächste Videos'],['Swipe to explore','Wischen zum Entdecken'],['MOVE WITH US','BEWEG DICH MIT UNS'],['Real movement. Real confidence.','Echte Bewegung. Echtes Selbstvertrauen.'],['AIRBRUSH IN MOTION','AIRBRUSH IN BEWEGUNG'],['The set, styled your way.','Das Set, dein Styling.'],
    ['Loved by our customers','Von unseren Kundinnen geliebt'],['Real experiences shared by our community','Echte Erfahrungen aus unserer Community'],['Previous reviews','Vorherige Bewertungen'],['Next reviews','Nächste Bewertungen'],
    ['YOUR SHOPPING BAG','DEIN WARENKORB'],['Your shopping bag is empty.','Dein Warenkorb ist leer.'],['Remove','Entfernen'],['Subtotal','Zwischensumme'],['CHECKOUT','ZUR KASSE'],['Added to your bag','Zum Warenkorb hinzugefügt'],['Please select an available size','Bitte wähle eine verfügbare Grösse'],
    ['PAGE NOT FOUND','SEITE NICHT GEFUNDEN'],['That page moved faster than we did.','Diese Seite ist nicht mehr verfügbar.'],['BACK HOME','ZUR STARTSEITE'],
    ['Full Length','Lang'],['Cropped','Kurz'],['Two fits · multiple colours','Zwei Passformen · mehrere Farben'],['7 colours','7 Farben']
  ];
  const chfValue=value=>{const n=Number(value)||0;if(n===9)return 9.95;if(n===13)return 14.95;if(n===17)return 19.95;if(n===25||n===26)return 29.95;return Math.round(n*1.15*20)/20};
  const chfMoney=value=>'CHF '+chfValue(value).toLocaleString('de-CH',{minimumFractionDigits:2,maximumFractionDigits:2});
  const convertPounds=html=>String(html).replace(/£\s*([\d,]+(?:\.\d+)?)/g,(_,raw)=>chfMoney(Number(raw.replace(/,/g,''))));
  const translateHtml=html=>convertPounds(replacements.reduce((value,pair)=>value.split(pair[0]).join(pair[1]),String(html)));
  const exact={'NEW':'NEU','SALE':'SALE','SHORTS':'SHORTS','BRAS':'SPORT-BHS','LEGGINGS':'LEGGINGS','TOPS':'TOPS','PANTS':'HOSEN','HOODIES':'HOODIES','ACCESSORIES':'ACCESSOIRES','DRESSES':'KLEIDER','Maat':'Grösse','Size':'Grösse'};
  const colours={'Black':'Schwarz','White':'Weiss','Navy':'Marineblau','Grey':'Grau','Gray':'Grau','Pink':'Rosa','Red':'Rot','Blue':'Blau','Green':'Grün','Brown':'Braun','Beige':'Beige','Purple':'Violett','Orange':'Orange','Yellow':'Gelb','Anthracite / White':'Anthrazit / Weiss','Black / White':'Schwarz / Weiss','Navy / White':'Marineblau / Weiss','White / Black':'Weiss / Schwarz','Grass':'Grasgrün','California Blue':'Kalifornienblau'};
  const colourName=value=>{const raw=String(value||'');const direct=Object.keys(colours).find(key=>key.toLowerCase()===raw.toLowerCase());return direct?colours[direct]:raw.replace(/Black/gi,'Schwarz').replace(/White/gi,'Weiss').replace(/Blue/gi,'Blau').replace(/Green/gi,'Grün').replace(/Grey|Gray/gi,'Grau').replace(/Pink/gi,'Rosa').replace(/Red/gi,'Rot').replace(/Brown/gi,'Braun').replace(/Purple/gi,'Violett')};
  const translateDom=(root=document.body)=>{if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{if(node.parentElement?.closest('script,style'))return;const raw=node.nodeValue,trim=raw.trim();if(!trim)return;node.nodeValue=raw.replace(trim,exact[trim]||colours[trim]||translateHtml(trim))})};
  const legal={
    about:['ÜBER VEROLAFIT','Wir entwickeln formende Activewear, die Stärke in jeder Form feiert. Unsere Mission ist, dass sich jede Frau grossartig fühlt.'],
    contact:['KONTAKT','Du brauchst Hilfe? Schreibe uns an support@example.com. Unser Kundenservice ist Montag bis Freitag von 9:00 bis 17:00 Uhr erreichbar.'],
    faq:['HILFE-CENTER','Hier findest du Antworten zu Bestellungen, Grössen, kostenloser Lieferung innerhalb von 48 Stunden, 60-Tage-Rückgabe, Zahlungen und Pflege.'],
    shipping:['KOSTENLOSE LIEFERUNG INNERHALB VON 48 STUNDEN','Alle Bestellungen in der Schweiz werden kostenlos geliefert. Dein Paket wird für die Zustellung innerhalb von 48 Stunden vorbereitet. Die Sendungsverfolgung erhältst du automatisch per E-Mail.'],
    returns:['60 TAGE KOSTENLOSE RÜCKGABE UND GARANTIE','Probiere jedes Produkt 60 Tage zu Hause. Wenn es nicht perfekt passt, kannst du es kostenlos und ohne Angabe eines Grundes zurücksenden. Die Erstattung erfolgt auf die ursprüngliche Zahlungsart.'],
    reviews:['MEHR ALS 5.000 ZUFRIEDENE KUNDINNEN','Unsere Community schätzt die schmeichelhafte Passform, weichen Materialien und den Komfort von Verolafit.'],
    terms:['ALLGEMEINE GESCHÄFTSBEDINGUNGEN','Diese Bedingungen gelten für die Nutzung des Shops und alle Bestellungen. Zwingende Rechte von Konsumentinnen und Konsumenten nach Schweizer Recht bleiben vollständig anwendbar.'],
    privacy:['DATENSCHUTZ UND SICHERE ZAHLUNG','Wir verwenden verschlüsselte Technologie zum Schutz deiner Zahlung. Wir verarbeiten nur Daten, die für Bestellung, Service und Verbesserung des Einkaufserlebnisses erforderlich sind.'],
    cookies:['COOKIE-RICHTLINIE','Diese Website verwendet notwendige Cookies für den Warenkorb und, mit deiner Einwilligung, Analyse-Cookies. Einstellungen können im Browser verwaltet werden.'],
    legal:['IMPRESSUM','Wichtig: Firmenname, UID, Handelsregisternummer, Geschäftsadresse und verifizierte Kontaktdaten sind Platzhalter und müssen vor dem kommerziellen Betrieb durch die Angaben des Verkäufers ersetzt werden.'],
    loyalty:['VEROLAFIT REWARDS','Schliesse dich mehr als 5.000 Kundinnen an und erhalte Belohnungen sowie frühzeitigen Zugang.'],
    'size-guide':['EU-GRÖSSENTABELLE','Entdecke die europäischen Grössen XS bis XXL mit den entsprechenden Körpermassen. Alle Produkte können 60 Tage kostenlos zurückgegeben werden.']
  };
  const baseHome=home,baseCollection=collection,baseProductPage=productPage,baseNotFound=notFound,baseBindPage=bindPage,baseRenderCart=renderCart;
  home=()=>translateHtml(baseHome());
  collection=slug=>translateHtml(baseCollection(slug));
  productPage=handle=>translateHtml(baseProductPage(handle));
  notFound=()=>translateHtml(baseNotFound());
  page=name=>{const value=legal[name]||['SEITE','Inhalt folgt in Kürze.'];return '<article class="legal"><h1>'+value[0]+'</h1><p>'+value[1]+'</p><h2>Wichtige Informationen</h2><p>Diese Seite wurde für den Schweizer Verolafit-Shop in deutscher Sprache erstellt. Gesetzliche Anbieterangaben müssen vor dem kommerziellen Betrieb ergänzt und geprüft werden.</p></article>'};
  checkout=()=>'<div class="checkout"><h1>ZUR KASSE</h1><div class="checkout-grid"><form id="checkoutForm"><h2>Kontakt</h2><input required type="email" placeholder="E-Mail-Adresse"><h2>Lieferadresse</h2><input required placeholder="Vorname"><input required placeholder="Nachname"><input required placeholder="Adresse"><input required placeholder="Ort"><input required placeholder="Postleitzahl"><select><option>Schweiz</option></select><h2>Zahlung</h2><p>Dies ist ein Demo-Shop. Es wird keine echte Zahlung ausgeführt.</p><button class="atc">DEMO-BESTELLUNG ABSCHLIESSEN</button></form><div><h2>Deine Bestellung</h2>'+cart.map(item=>'<div class="cart-line"><img src="'+item.image+'"><div><b>'+esc(item.title)+'</b><br><small>'+esc(item.variant||'')+'</small></div><b>'+chfMoney(item.price)+'</b></div>').join('')+'<h2>Gesamt '+chfMoney(cart.reduce((sum,item)=>sum+item.price,0))+'</h2></div></div></div>';
  const sizes=['XS','S','M','L','XL','XXL'];
  const sizeButtons=(classes,kind='')=>sizes.map((size,index)=>'<button class="choice '+classes+' '+(index===1?'active':'')+'" '+(kind?'data-kind="'+kind+'"':'')+' data-size="'+size+'" data-value="'+size+'">'+size+'</button>').join('');
  const bindGroup=selector=>document.querySelectorAll(selector).forEach(button=>button.onclick=()=>{document.querySelectorAll(selector).forEach(item=>item.classList.remove('active'));button.classList.add('active')});
  function localizeProduct(){
    if(location.hash.endsWith('define-jacket-nulu')){const group=$('.lulu-sizes');if(group){group.innerHTML=sizeButtons('lulu-size');bindGroup('.lulu-size')}document.querySelectorAll('.lulu-product .colour-swatch').forEach(button=>button.title=colourName(button.dataset.colour));const current=$('.lulu-current-colour');if(current)current.textContent=colourName($('.colour-swatch.active')?.dataset.colour||current.textContent);const guide=$('#sizeGuidePanel .size-table-wrap');if(guide)guide.innerHTML='<table><thead><tr><th>Grösse</th><th>EU</th><th>Brust</th><th>Taille</th><th>Hüfte</th></tr></thead><tbody><tr><td>XS</td><td>34</td><td>80–84</td><td>62–66</td><td>86–90</td></tr><tr><td>S</td><td>36</td><td>84–88</td><td>66–70</td><td>90–94</td></tr><tr><td>M</td><td>38</td><td>88–92</td><td>70–74</td><td>94–98</td></tr><tr><td>L</td><td>40</td><td>92–98</td><td>74–80</td><td>98–104</td></tr><tr><td>XL</td><td>42</td><td>98–104</td><td>80–86</td><td>104–110</td></tr><tr><td>XXL</td><td>44–46</td><td>104–112</td><td>86–94</td><td>110–118</td></tr></tbody></table><p>Körpermasse in cm. Wenn du zwischen zwei Grössen liegst, wähle die grössere.</p>'}
    if(location.hash.endsWith('airbrush-set')){const top=$('.air-top-sizes'),bottom=$('.air-bottom-sizes');if(top&&bottom){top.innerHTML=sizeButtons('air-size','top');bottom.innerHTML=sizeButtons('air-size','bottom');bindGroup('.air-size[data-kind="top"]');bindGroup('.air-size[data-kind="bottom"]')}const guide=$('#airSizePanel .size-table-wrap');if(guide)guide.innerHTML='<h3>SPORT-BH</h3><table><thead><tr><th>Grösse</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>EU-Unterbrust</th><td>65</td><td>70</td><td>75</td><td>80</td><td>85</td><td>90</td></tr></tbody></table><h3>HOSE</h3><table><thead><tr><th>Grösse</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>EU</th><td>34</td><td>36</td><td>38</td><td>40</td><td>42</td><td>44–46</td></tr></tbody></table><p>Die Grössen für Oberteil und Hose können separat gewählt werden.</p>'}
    if(location.hash.endsWith('unisex-half-crew-throwback-sock'))$('.sock-reviews')?.remove();
    translateDom(document.querySelector('main'));
  }
  renderCart=function(){baseRenderCart();translateDom($('.cart-panel'))};
  bindPage=function(){
    baseBindPage();localizeProduct();
    $('#searchBtn').onclick=()=>{const query=prompt('Produkte suchen');if(query)location.hash='/collection/'+encodeURIComponent(query)};
    const form=$('#checkoutForm');if(form)form.onsubmit=event=>{event.preventDefault();cart=[];saveCart();event.target.innerHTML='<h2>VIELEN DANK</h2><p>Deine Demo-Bestellung wurde empfangen.</p><a class="btn" href="#/">WEITER SHOPPEN</a>'};
    if(location.hash.endsWith('define-jacket-nulu')){const product=products.find(item=>item.handle==='define-jacket-nulu');$('#addToCart').onclick=()=>{const model=$('.model-choice.active')?.dataset.model,colour=$('.colour-swatch.active')?.dataset.colour,size=$('.lulu-size.active')?.dataset.size;if(!model||!colour||!size)return toast('Bitte Passform, Farbe und Grösse wählen');const variant=product.variants.find(item=>item.options[0].value===model&&item.options[1].value===colour&&item.available);if(!variant)return toast('Bitte eine verfügbare Variante wählen');location.href=buildMolipyUrl('https://www.molipy8trk.com/938L6R/PHK1H6Q/','DEFINE',[{productName:model==='Cropped'?'Define Cropped Jacket Nulu':'Define Jacket Nulu',model:colour,size,imageUrl:variant.image},{productName:'Lululemon Sport Bottle 24oz Straw Lid',model:'Gratisgeschenk',imageUrl:'https://images.lululemon.com/is/image/lululemon/LU9BA8S_0002_1?size=1200,1200'}])}}
    if(location.hash.endsWith('airbrush-set')){const product=products.find(item=>item.handle==='airbrush-set');$('#addToCart').onclick=()=>{const colour=$('.air-colours .active')?.dataset.colour,top=$('.air-top-sizes .active')?.dataset.size,bottom=$('.air-bottom-sizes .active')?.dataset.size,image=$('.air-colours .active')?.dataset.image;if(!colour||!top||!bottom||!image)return toast('Bitte Farbe und beide Grössen wählen');location.href=buildMolipyUrl('https://www.molipy8trk.com/938L6R/PGWZ1LT/Global','AIRBRUSH',[{productName:'Airbrush Sports Bra',color:colour,size:top,imageUrl:image},{productName:'Airbrush Bottom',color:colour,size:bottom,imageUrl:image},{productName:'Alo Yoga Tote Bag',model:'Gratisgeschenk',imageUrl:product.gift.image}])}}
  };
  renderCart();render();
})();
