(function(){
  const baseProductPage=productPage,baseBindPage=bindPage;
  const translations={
    en:{title:'Unisex Half-Crew Throwback Sock',stock:'In stock — ready to ship',colour:'SELECT COLOUR',size:'SELECT SIZE',guide:'SIZE GUIDE',pack:'CHOOSE YOUR PACK',packs:['1 PAIR','2 PAIRS','3 PAIRS'],pair:'PAIR',chooseColour:'Choose a colour',save:['','SAVE £5','SAVE £10'],atc:'ADD SOCKS TO BAG',description:'Description',body:'Instant classic. The Unisex Half-Crew Throwback Sock has all the features of a fave: a super-soft feel, comfy cushioning and classic stripe detail. Wear it tall or scrunched with leggings or shorts and your go-to sneakers.',fabrication:'Fabrication',fabric:'Combed cotton, nylon, lycra',shipping:'Free shipping within 48 hours',returns:'Free 60-day returns',sizeTitle:'SOCK SIZE GUIDE',shoe:'UK shoe size',measure:'Choose your regular sock size. If you are between sizes, choose the larger size.',added:'Socks added to your bag',close:'Close size guide'},
    es:{title:'Calcetines unisex Half-Crew Throwback',stock:'En stock — listo para enviar',colour:'ELIGE EL COLOR',size:'ELIGE LA TALLA',guide:'GUÍA DE TALLAS',pack:'ELIGE TU PACK',packs:['1 PAR','2 PARES','3 PARES'],pair:'PAR',chooseColour:'Elige un color',save:['','AHORRA 5 €','AHORRA 10 €'],atc:'AÑADIR CALCETINES A LA BOLSA',description:'Descripción',body:'Un clásico instantáneo. Los calcetines unisex Half-Crew Throwback tienen todo lo necesario para convertirse en tus favoritos: tacto ultrasuave, amortiguación cómoda y rayas clásicas. Llévalos altos o fruncidos con leggings, shorts y tus zapatillas favoritas.',fabrication:'Composición',fabric:'Algodón peinado, nailon y licra',shipping:'Envío gratis en 48 horas',returns:'Devoluciones gratis durante 60 días',sizeTitle:'GUÍA DE TALLAS DE CALCETINES',shoe:'Talla de calzado EU',measure:'Elige tu talla habitual de calcetines. Si estás entre dos tallas, elige la más grande.',added:'Calcetines añadidos a tu bolsa',close:'Cerrar guía de tallas'},
    nl:{title:'Unisex Half-Crew Throwback sokken',stock:'Op voorraad — klaar voor verzending',colour:'KIES DE KLEUR',size:'KIES JE MAAT',guide:'EU MAATTABEL',pack:'KIES JE PAKKET',packs:['1 PAAR','2 PAAR','3 PAAR'],pair:'PAAR',chooseColour:'Kies een kleur',save:['','BESPAAR 5 €','BESPAAR 10 €'],atc:'VOEG SOKKEN TOE AAN WINKELMAND',description:'Beschrijving',body:'Een instant klassieker. De unisex Half-Crew Throwback sokken hebben alles wat je van een favoriet verwacht: een superzacht gevoel, comfortabele demping en klassieke strepen. Draag ze hoog of nonchalant met een legging, short en je favoriete sneakers.',fabrication:'Samenstelling',fabric:'Gekamd katoen, nylon en lycra',shipping:'Gratis verzending in Nederland binnen 48 uur',returns:'60 dagen gratis retourneren',sizeTitle:'EU MAATTABEL VOOR SOKKEN',shoe:'EU schoenmaat',measure:'Kies je gebruikelijke sokkenmaat. Zit je tussen twee maten in, kies dan de grotere maat.',added:'Sokken toegevoegd aan je winkelmand',close:'Maattabel sluiten'}
  };
  const localeCopy=translations[document.documentElement.lang]?document.documentElement.lang:'en';
  const t=translations[localeCopy];
  const serviceDetails={
    en:{shipping:'<p>Standard delivery is completely free on every order in the United Kingdom, with no minimum spend. Your parcel is prepared promptly for delivery within 48 hours. As soon as it leaves our warehouse, you will receive an email with tracking information so you can follow every step.</p><ul><li>Free delivery throughout the United Kingdom</li><li>Expected delivery within 48 hours</li><li>Tracking sent automatically by email</li></ul>',returns:'<p>Try your socks at home with complete peace of mind. You have 60 days from delivery to request a return. Returns are free and no explanation is required.</p><ul><li>Contact customer care to receive your prepaid return label</li><li>Send the parcel back free of charge</li><li>Your refund is issued to the original payment method after the return is received</li></ul>'},
    es:{shipping:'<p>La entrega estándar es totalmente gratuita en todos los pedidos enviados a España, sin importe mínimo. Preparamos tu paquete rápidamente para que llegue en un plazo de 48 horas. Cuando salga de nuestro almacén, recibirás automáticamente un correo electrónico con el seguimiento.</p><ul><li>Entrega gratuita en toda España</li><li>Entrega prevista en 48 horas</li><li>Seguimiento enviado automáticamente por correo electrónico</li></ul>',returns:'<p>Prueba tus calcetines en casa con total tranquilidad. Dispones de 60 días desde la entrega para solicitar una devolución. La devolución es gratuita y no tienes que dar ninguna explicación.</p><ul><li>Contacta con atención al cliente para recibir la etiqueta de devolución prepagada</li><li>Devuelve el paquete sin ningún coste</li><li>El reembolso se realiza en el método de pago original cuando recibimos la devolución</li></ul>'},
    nl:{shipping:'<p>Standaardbezorging is volledig gratis voor iedere bestelling in Nederland, zonder minimumbedrag. We maken je pakket snel klaar voor bezorging binnen 48 uur. Zodra het ons magazijn verlaat, ontvang je automatisch een e-mail met de track-en-trace.</p><ul><li>Gratis bezorging in heel Nederland</li><li>Verwachte bezorging binnen 48 uur</li><li>Track-en-trace automatisch per e-mail</li></ul>',returns:'<p>Probeer je sokken thuis met volledige zekerheid. Vanaf de bezorgdatum heb je 60 dagen om een retour aan te vragen. Retourneren is gratis en je hoeft geen reden op te geven.</p><ul><li>Neem contact op met de klantenservice voor een vooraf betaald retourlabel</li><li>Stuur het pakket kosteloos terug</li><li>Na ontvangst van de retour betalen we terug via de oorspronkelijke betaalmethode</li></ul>'}
  };
  const service=serviceDetails[localeCopy];
  const prices={en:[9,13,17],es:[9.99,14.95,19.99],nl:[9.99,14.95,19.99]};
  const checkoutUrls=['https://www.molipy8trk.com/938L6R/PHB33HP/Global','https://www.molipy8trk.com/938L6R/PHG7PPJ/Global','https://www.molipy8trk.com/938L6R/PHK1H6Q/'];
  const formatPrice=value=>localeCopy==='en'?'£'+value.toFixed(2):`${value.toLocaleString(localeCopy==='es'?'es-ES':'nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})} €`;
  const colourTranslations={es:{'White/California Blue':'Blanco/Azul California','White/Pink Marshmallow':'Blanco/Rosa Marshmallow','Pink Marshmallow/White':'Rosa Marshmallow/Blanco','Dune Grass/White':'Verde hierba/Blanco','White/Satsuma Breeze':'Blanco/Naranja Satsuma','White/Emerald Isle':'Blanco/Verde esmeralda','White Heather/Grey':'Blanco jaspeado/Gris','White/Azure Blue':'Blanco/Azul celeste','White/Summer Romance Red':'Blanco/Rojo','White/Sun Kissed Brown':'Blanco/Marrón','Oatmeal Heather/White':'Avena jaspeado/Blanco','Navy/White':'Azul marino/Blanco','White/Navy':'Blanco/Azul marino','Espresso/White':'Café/Blanco','White/Titanium':'Blanco/Titanio','Athletic Heather Grey/White':'Gris jaspeado/Blanco','Black/White':'Negro/Blanco','White/Black':'Blanco/Negro','Gravel/White':'Gris piedra/Blanco','Bone/White':'Hueso/Blanco'},nl:{'White/California Blue':'Wit/Californiëblauw','White/Pink Marshmallow':'Wit/Marshmallowroze','Pink Marshmallow/White':'Marshmallowroze/Wit','Dune Grass/White':'Grasgroen/Wit','White/Satsuma Breeze':'Wit/Satsuma-oranje','White/Emerald Isle':'Wit/Smaragdgroen','White Heather/Grey':'Gemêleerd wit/Grijs','White/Azure Blue':'Wit/Azuurblauw','White/Summer Romance Red':'Wit/Rood','White/Sun Kissed Brown':'Wit/Bruin','Oatmeal Heather/White':'Gemêleerd havermout/Wit','Navy/White':'Marineblauw/Wit','White/Navy':'Wit/Marineblauw','Espresso/White':'Espresso/Wit','White/Titanium':'Wit/Titanium','Athletic Heather Grey/White':'Gemêleerd grijs/Wit','Black/White':'Zwart/Wit','White/Black':'Wit/Zwart','Gravel/White':'Steengrijs/Wit','Bone/White':'Crème/Wit'}};
  const colourName=name=>colourTranslations[localeCopy]?.[name]||name;
  const reviewImages=['https://videos.mybookusa.com/11/Capture%20d%E2%80%99e%CC%81cran%202026-09-06%20a%CC%80%2003.56.27.png','https://videos.mybookusa.com/11/Capture%20d%E2%80%99e%CC%81cran%202026-09-06%20a%CC%80%2003.56.21.png','https://videos.mybookusa.com/11/Capture%20d%E2%80%99e%CC%81cran%202026-09-06%20a%CC%80%2003.56.16.png','https://videos.mybookusa.com/11/Capture%20d%E2%80%99e%CC%81cran%202026-09-06%20a%CC%80%2003.56.10.png'];
  const sockReviews=()=>{const copy=localeCopy==='es'?{eyebrow:'COMUNIDAD VEROLAFIT',title:'Opiniones de nuestras clientas',subtitle:'Experiencias reales, compartidas por nuestra comunidad',previous:'Opiniones anteriores',next:'Opiniones siguientes'}:localeCopy==='nl'?{eyebrow:'VEROLAFIT COMMUNITY',title:'Wat onze klanten zeggen',subtitle:'Echte ervaringen van onze community',previous:'Vorige reviews',next:'Volgende reviews'}:{eyebrow:'VEROLAFIT COMMUNITY',title:'Loved by our customers',subtitle:'Real experiences shared by our community',previous:'Previous reviews',next:'Next reviews'};return `<section class="sock-reviews"><div class="sock-reviews-head"><div><small>${copy.eyebrow}</small><h2>${copy.title}</h2><p>${copy.subtitle}</p></div><div class="sock-review-nav"><button id="sockReviewPrev" type="button" aria-label="${copy.previous}">←</button><button id="sockReviewNext" type="button" aria-label="${copy.next}">→</button></div></div><div class="sock-review-track" id="sockReviewTrack">${reviewImages.map((image,index)=>`<article class="sock-review-card"><img src="${image}" alt="${copy.title} ${index+1}" loading="lazy"></article>`).join('')}</div></section>`};
  const sizeGuide=()=>`<div class="review-backdrop" id="sockSizePanel"><section class="review-modal size-guide-modal" role="dialog" aria-modal="true" aria-label="${t.sizeTitle}"><button class="review-close" id="sockSizeClose" aria-label="${t.close}">×</button><div class="review-summary"><b>${t.sizeTitle}</b></div><div class="size-table-wrap"><table><thead><tr><th>${localeCopy==='en'?'Size':localeCopy==='es'?'Talla':'Maat'}</th><th>S</th><th>M</th><th>L</th></tr></thead><tbody><tr><th>${t.shoe}</th><td>${localeCopy==='en'?'3–5':'35–37'}</td><td>${localeCopy==='en'?'5.5–7.5':'38–40'}</td><td>${localeCopy==='en'?'8–11':'41–44'}</td></tr></tbody></table><p>${t.measure}</p></div></section></div>`;
  function socksPage(p){const selected=p.colourData[0],gallery=selected.images.slice(0,4),localPrices=prices[localeCopy];return `<div class="product-page socks-product"><div class="gallery socks-gallery">${gallery.map((image,index)=>`<img src="${image}" alt="${t.title} ${colourName(selected.name)} ${index+1}">`).join('')}</div><section class="details"><div class="colour">ALO YOGA</div><h1>${t.title}</h1><div class="stock title-stock"><i></i> ${t.stock}</div><div class="price socks-price"><b>${formatPrice(localPrices[0])}</b></div><p><b>${t.colour}</b> · <span class="sock-colour-name">${colourName(selected.name)}</span></p><div class="colour-swatches sock-colours">${p.colourData.map((entry,index)=>`<button class="colour-swatch ${index===0?'active':''}" data-colour="${esc(entry.name)}" data-images='${esc(JSON.stringify(entry.images))}' title="${esc(colourName(entry.name))}"><img src="${entry.images[0]}" alt="${esc(colourName(entry.name))}"></button>`).join('')}</div><div class="size-label"><b>${t.size}</b><button id="sockSizeOpen">${t.guide}</button></div><div class="choices sock-sizes">${['S','M','L'].map((size,index)=>`<button class="choice sock-size ${index===1?'active':''}" data-size="${size}">${size}</button>`).join('')}</div><p><b>${t.pack}</b></p><div class="sock-packs">${[1,2,3].map((quantity,index)=>`<button class="sock-pack ${index===0?'active':''}" data-index="${index}" data-quantity="${quantity}" data-base-price="${p.packs[index].price}"><span>${t.packs[index]}</span><b>${formatPrice(localPrices[index])}</b>${t.save[index]?`<small>${t.save[index]}</small>`:''}</button>`).join('')}</div><div id="sockExtraPairs"></div><button class="atc" id="addToCart">${t.atc}</button>${sizeGuide()}<div class="tabs"><details open><summary>${t.description}</summary><p>${t.body}</p></details><details><summary>${t.fabrication}</summary><p>${t.fabric}</p></details><details><summary>${t.shipping}</summary><div class="service-copy">${service.shipping}</div></details><details><summary>${t.returns}</summary><div class="service-copy">${service.returns}</div></details></div>${sockReviews()}</section></div>${shelf(localeCopy==='es'?'TAMBIÉN TE PUEDE GUSTAR':localeCopy==='nl'?'MISSCHIEN VIND JE DIT OOK LEUK':'YOU MAY ALSO LIKE',localeCopy==='es'?'Completa el look':localeCopy==='nl'?'Maak je look compleet':'Complete the look',pick('accessories',8).filter(x=>x.handle!==p.handle),'accessories')}`}
  productPage=function(handle){if(handle!=='unisex-half-crew-throwback-sock')return baseProductPage(handle);return socksPage(products.find(product=>product.handle===handle))};
  bindPage=function(){
    baseBindPage();
    if(!location.hash.endsWith('unisex-half-crew-throwback-sock'))return;
    const product=products.find(item=>item.handle==='unisex-half-crew-throwback-sock');
    const extraPairs=$('#sockExtraPairs');
    const renderExtraPairs=quantity=>{
      extraPairs.className='sock-extra-pairs';
      extraPairs.innerHTML=Array.from({length:quantity},(_,offset)=>{
        const pairNumber=offset+1,activeColour=$('.sock-colours .active')?.dataset.colour,selected=offset===0?product.colourData.find(entry=>entry.name===activeColour)||product.colourData[0]:product.colourData[offset]||product.colourData[0],activeSize=$('.sock-size.active')?.dataset.size||'M';
        return `<div class="sock-pair-config" data-pair="${pairNumber}"><img src="${selected.images[0]}" alt="${esc(colourName(selected.name))}"><div class="sock-pair-fields"><strong>${t.pair} ${pairNumber}</strong><div class="sock-pair-row"><select class="sock-pair-colour" aria-label="${t.pair} ${pairNumber} — ${t.chooseColour}">${product.colourData.map(entry=>`<option value="${esc(entry.name)}" data-image="${entry.images[0]}" ${entry===selected?'selected':''}>${esc(colourName(entry.name))}</option>`).join('')}</select><div class="sock-pair-sizes">${['S','M','L'].map(size=>`<button class="sock-pair-size ${size===(offset===0?activeSize:'M')?'active':''}" type="button" data-size="${size}">${size}</button>`).join('')}</div></div></div></div>`;
      }).join('');
      extraPairs.querySelectorAll('.sock-pair-colour').forEach(select=>select.onchange=()=>{const option=select.selectedOptions[0],pair=select.closest('.sock-pair-config');pair.querySelector('img').src=option.dataset.image;if(pair.dataset.pair==='1')document.querySelector(`.sock-colours [data-colour="${CSS.escape(select.value)}"]`)?.click()});
      extraPairs.querySelectorAll('.sock-pair-size').forEach(sizeButton=>sizeButton.onclick=()=>{const group=sizeButton.closest('.sock-pair-sizes'),pair=sizeButton.closest('.sock-pair-config');group.querySelectorAll('.sock-pair-size').forEach(item=>item.classList.remove('active'));sizeButton.classList.add('active');if(pair.dataset.pair==='1')document.querySelector(`.sock-size[data-size="${sizeButton.dataset.size}"]`)?.click()});
    };
    document.querySelectorAll('.sock-colours .colour-swatch').forEach(colourButton=>colourButton.onclick=()=>{document.querySelectorAll('.sock-colours .colour-swatch').forEach(item=>item.classList.remove('active'));colourButton.classList.add('active');$('.sock-colour-name').textContent=colourName(colourButton.dataset.colour);const images=JSON.parse(colourButton.dataset.images);$('.socks-gallery').innerHTML=images.slice(0,4).map((image,index)=>`<img src="${image}" alt="${t.title} ${colourName(colourButton.dataset.colour)} ${index+1}">`).join('');const pairOne=extraPairs.querySelector('[data-pair="1"]');if(pairOne){const select=pairOne.querySelector('.sock-pair-colour');select.value=colourButton.dataset.colour;pairOne.querySelector('img').src=colourButton.querySelector('img').src}});
    document.querySelectorAll('.sock-size').forEach(sizeButton=>sizeButton.onclick=()=>{document.querySelectorAll('.sock-size').forEach(item=>item.classList.remove('active'));sizeButton.classList.add('active');const pairOne=extraPairs.querySelector('[data-pair="1"]');if(pairOne){pairOne.querySelectorAll('.sock-pair-size').forEach(item=>item.classList.toggle('active',item.dataset.size===sizeButton.dataset.size))}});
    document.querySelectorAll('.sock-pack').forEach(packButton=>packButton.onclick=()=>{document.querySelectorAll('.sock-pack').forEach(item=>item.classList.remove('active'));packButton.classList.add('active');$('.socks-price b').textContent=formatPrice(prices[localeCopy][Number(packButton.dataset.index)]);renderExtraPairs(Number(packButton.dataset.quantity))});
    const panel=$('#sockSizePanel'),close=()=>{panel.classList.remove('open');document.body.classList.remove('modal-open')};
    $('#sockSizeOpen').onclick=()=>{panel.classList.add('open');document.body.classList.add('modal-open')};
    $('#sockSizeClose').onclick=close;
    panel.onclick=event=>{if(event.target===panel)close()};
    renderExtraPairs(1);
    const reviewTrack=$('#sockReviewTrack'),reviewStep=()=>reviewTrack.clientWidth*.52;
    $('#sockReviewPrev').onclick=()=>reviewTrack.scrollBy({left:-reviewStep(),behavior:'smooth'});
    $('#sockReviewNext').onclick=()=>reviewTrack.scrollBy({left:reviewStep(),behavior:'smooth'});
    const button=$('#addToCart');
    if(!button)return;
    button.onclick=()=>{
      const packButton=$('.sock-pack.active');
      if(!packButton)return toast(localeCopy==='es'?'Selecciona un pack':localeCopy==='nl'?'Kies een pakket':'Select a pack');
      const quantity=Number(packButton.dataset.quantity),tierIndex=Number(packButton.dataset.index),items=[];
      extraPairs.querySelectorAll('.sock-pair-config').forEach(pair=>{const select=pair.querySelector('.sock-pair-colour'),option=select.selectedOptions[0],extraSize=pair.querySelector('.sock-pair-size.active');items.push({productName:'Unisex Half-Crew Throwback Sock',color:select.value,size:extraSize?.dataset.size,imageUrl:option.dataset.image})});
      if(items.length!==quantity||items.some(item=>!item.color||!item.size||!item.imageUrl))return toast(localeCopy==='es'?'Configura cada par antes de continuar':localeCopy==='nl'?'Stel elk paar samen voordat je doorgaat':'Configure every pair before continuing');
      location.href=buildMolipyUrl(checkoutUrls[tierIndex],'ALO-SOCKS',items);
    };
  };
  render();
})();
