(function(){
  const replacements=[
    ['BUILT FOR STRENGTH','DISEÑADO PARA TU FUERZA'],['Made for every shake and hold — movement that feels like you.','Creado para acompañar cada movimiento y hacerte sentir increíble.'],['SHOP NOW','COMPRAR AHORA'],
    ['NEW RELEASES','NOVEDADES'],['Explore our latest products','Descubre nuestros últimos productos'],['Shop all','Ver todo'],['OWN YOUR JOURNEY','HAZ TUYO EL CAMINO'],['Stories of Strength Capsule','Colección Historias de Fuerza'],['BUILD YOUR WISHLIST','CREAR MI LISTA'],
    ['BEST SELLERS','MÁS VENDIDOS'],['Your favourites, right here','Tus favoritos, aquí mismo'],['SHOP BY CATEGORY','COMPRAR POR CATEGORÍA'],['Find your movement essential','Encuentra tus imprescindibles'],['JUST FOR YOU','PARA TI'],['Our top recommendations','Nuestras recomendaciones'],
    ['products','productos'],['Search this collection','Buscar en esta colección'],['Featured','Destacados'],['Price: low to high','Precio: de menor a mayor'],['Price: high to low','Precio: de mayor a menor'],['All categories','Todas las categorías'],
    ['In stock — ready to ship','En stock — listo para enviar'],['In stock — all sizes available','En stock — todas las tallas disponibles'],['SELECT FIT','ELIGE EL CORTE'],['SELECT COLOUR','ELIGE EL COLOR'],['SELECT US SIZE (UK SIZE)','ELIGE LA TALLA'],['UK SIZE GUIDE','GUÍA DE TALLAS'],
    ['ADD TO BAG','AÑADIR A LA BOLSA'],['ADD THE COMPLETE SET TO BAG','AÑADIR EL CONJUNTO COMPLETO'],['5,000+ happy customers','Más de 5.000 clientes felices'],['Read reviews','Leer opiniones'],['Read Airbrush Set reviews','Leer opiniones del Airbrush Set'],
    ['FREE 48H SHIPPING','ENVÍO GRATIS EN 48 H'],['On every UK order','En todos los pedidos'],['60-DAY RETURNS','DEVOLUCIONES 60 DÍAS'],['Free, no questions asked','Gratis y sin preguntas'],['SECURE PAYMENT','PAGO SEGURO'],['SSL encrypted checkout','Pago cifrado SSL'],
    ['YOUR COMPLIMENTARY GIFT','TU REGALO INCLUIDO'],['FREE GIFT WITH YOUR SET','REGALO GRATIS CON TU CONJUNTO'],['Automatically included in your parcel — no code needed.','Incluido automáticamente en tu paquete — sin código.'],['FREE','GRATIS'],
    ['COMPLETE 2-PIECE SET','CONJUNTO COMPLETO DE 2 PIEZAS'],['Sports bra + matching bottom','Sujetador + parte inferior a juego'],['SELECT COLOUR','ELIGE EL COLOR'],['1. CHOOSE YOUR TOP SIZE','1. ELIGE LA TALLA DE ARRIBA'],['2. CHOOSE YOUR BOTTOM SIZE','2. ELIGE LA TALLA DE ABAJO'],
    ['Excellent','Excelente'],['Based on 649 product reviews','Basado en 649 opiniones'],['Loved by 5,000+ customers','Elegido por más de 5.000 clientes'],['Verified customer','Compra verificada'],
    ['4.81 out of 5','4,81 de 5'],['4.9 out of 5','4,9 de 5'],['4.8 out of 5','4,8 de 5'],['Based on 5,127 customer reviews','Basado en 5.127 opiniones de clientes'],['Close reviews','Cerrar opiniones'],['Customer reviews','Opiniones de clientes'],['Airbrush Set reviews','Opiniones del Airbrush Set'],
    ['Soft, sculpting and flattering','Suave, moldeadora y favorecedora'],['The fabric is super soft and both jacket lengths give a beautiful sculpted silhouette.','El tejido es muy suave y los dos largos de chaqueta crean una silueta preciosa y moldeada.'],['I love having both fits','Me encanta poder elegir entre los dos cortes'],['The cropped fit is perfect with high-rise leggings while the full length is my everyday favourite.','El corte cropped queda perfecto con leggings de tiro alto, mientras que el largo es mi favorito para cada día.'],['Amazing jacket family','Una colección de chaquetas increíble'],['The close fit is flattering and the Nulu fabric stays soft enough for all-day wear.','El corte ajustado favorece muchísimo y el tejido Nulu permanece suave durante todo el día.'],
    ['The best matching set','El mejor conjunto a juego'],['The fabric is smooth, supportive and so flattering. I love that I could choose a different size for my bra and leggings.','El tejido es suave, ofrece una gran sujeción y favorece muchísimo. Me encanta poder elegir una talla distinta para el sujetador y los leggings.'],['Looks expensive','Parece un conjunto de lujo'],['The Airbrush set fits beautifully and stays in place through my full workout. The free tote is such a nice bonus.','El conjunto Airbrush sienta genial y no se mueve durante todo el entrenamiento. El bolso tote gratis es un detalle fantástico.'],['Immediately ordered another colour','Pedí otro color inmediatamente'],['Soft, sculpting and completely squat proof. For £25, this two-piece set is incredible.','Suave, moldeador y totalmente opaco al hacer sentadillas. Por £25, este conjunto de dos piezas es increíble.'],
    ['It gives me the same polished look I love in my Lululemon Define Jacket, but feels lighter for everyday wear.','Me da el mismo acabado elegante que me encanta de mi chaqueta Lululemon Define, pero resulta más ligera para el día a día.'],['The waist is so flattering and the stretch is perfect. I have worn it for Pilates, errands and travel.','La cintura favorece muchísimo y la elasticidad es perfecta. La he usado para pilates, recados y viajes.'],['I immediately ordered another colour.','Pedí otro color inmediatamente.'],
    ['Choose your fit','Elige tu corte'],['Fit and features','Corte y características'],['Free 48-hour shipping','Envío gratis en 48 horas'],['Free 60-day returns','Devoluciones gratis durante 60 días'],['60-day guarantee','Garantía de 60 días'],['Product details','Detalles del producto'],['What is included?','¿Qué incluye?'],['Fit & fabric','Corte y tejido'],
    ['YOU MAY ALSO LIKE','TAMBIÉN TE PUEDE GUSTAR'],['Complete the look','Completa el look'],['COMPLETE THE LOOK','COMPLETA EL LOOK'],['More movement essentials','Más prendas esenciales'],
    ['Everyday sculpt','Moldea tu día'],['Made to move','Hecho para moverte'],['Your strongest self','Tu versión más fuerte'],['Confidence in motion','Confianza en movimiento'],['Play video','Reproducir vídeo'],
    ['slim fit that sits at the hip.','corte ajustado que llega hasta la cadera.'],['waist length, designed to pair perfectly with high-rise bottoms.','largo hasta la cintura, diseñado para combinar con prendas de tiro alto.'],['Soft Nulu™ fabric, zippered pockets, thumbholes and Cuffins™, locker loop, zipper garage and an elastic hair-tie zipper pull.','Tejido Nulu™ suave, bolsillos con cremallera, aberturas para los pulgares y acabados cómodos.'],['Every UK order qualifies for free delivery, dispatched for arrival within 48 hours.','Todos los pedidos incluyen envío gratis con entrega prevista en 48 horas.'],['Try it at home for 60 days. Returns are free and refunded with no questions asked.','Pruébalo en casa durante 60 días. Las devoluciones son gratuitas y te reembolsamos sin preguntas.'],
    ['The perfect Define Jacket alternative','La alternativa perfecta a la Define Jacket'],['Flattering and true to size','Favorecedora y fiel a la talla'],['My new everyday layer','Mi nueva chaqueta para cada día'],['Beautiful sculpted fit and incredibly soft fabric.','Corte moldeador precioso y tejido increíblemente suave.'],['Premium finish, smooth zip and a close fit without feeling restrictive.','Acabado premium, cremallera suave y corte ajustado sin limitar el movimiento.'],
    ['Previous videos','Vídeos anteriores'],['Next videos','Vídeos siguientes'],['Swipe to explore','Desliza para descubrir'],['MOVE WITH US','MUÉVETE CON NOSOTRAS'],['Real movement. Real confidence.','Movimiento real. Confianza real.'],['AIRBRUSH IN MOTION','AIRBRUSH EN MOVIMIENTO'],['The set, styled your way.','El conjunto, a tu manera.'],
    ['YOUR SHOPPING BAG','TU BOLSA'],['Your shopping bag is empty.','Tu bolsa está vacía.'],['Remove','Eliminar'],['Subtotal','Subtotal'],['CHECKOUT','FINALIZAR COMPRA'],['Added to your bag','Añadido a tu bolsa'],['Please select an available size','Selecciona una talla'],
    ['PAGE NOT FOUND','PÁGINA NO ENCONTRADA'],['That page moved faster than we did.','Esta página ya no está disponible.'],['BACK HOME','VOLVER AL INICIO']
  ];
  const euroValue=value=>{const n=Number(value)||0;return n===25?29:n===17?19.99:Math.round(n*1.16)};
  const euroMoney=value=>`${euroValue(value).toLocaleString('es-ES')} €`;
  const convertPounds=html=>String(html).replace(/£\s*([\d,]+(?:\.\d+)?)/g,(_,raw)=>euroMoney(Number(raw.replace(/,/g,''))));
  const translateHtml=html=>convertPounds(replacements.reduce((s,[a,b])=>s.split(a).join(b),html));
  const exactEs={'NEW':'NUEVO','SALE':'OFERTA','SHORTS':'SHORTS','BRAS':'SUJETADORES','LEGGINGS':'LEGGINGS','TOPS':'TOPS','PANTS':'PANTALONES','HOODIES':'SUDADERAS','ACCESSORIES':'ACCESORIOS','DRESSES':'VESTIDOS','Full Length':'Largo','Cropped':'Corto','Two fits · multiple colours':'Dos cortes · varios colores','7 colours':'7 colores'};
  const translateDom=(root=document.body)=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.parentElement?.closest('script,style'))return;const raw=n.nodeValue,trim=raw.trim(),translated=exactEs[trim]||colourEs[trim]||translateHtml(trim);n.nodeValue=raw.replace(trim,translated)})};
  const colourEs={'Black':'Negro','White':'Blanco','Navy':'Azul marino','Grey':'Gris','Gray':'Gris','Pink':'Rosa','Red':'Rojo','Blue':'Azul','Green':'Verde','Brown':'Marrón','Beige':'Beige','Purple':'Morado','Orange':'Naranja','Yellow':'Amarillo','Anthracite/White':'Antracita/Blanco','Anthracite / White':'Antracita / Blanco','Black White':'Negro/Blanco','Black / White':'Negro / Blanco','Navy White':'Azul marino/Blanco','Navy / White':'Azul marino / Blanco','White Black':'Blanco/Negro','White / Black':'Blanco / Negro','Grass':'Verde hierba','California Blue':'Azul California'};
  const colourWords={'Black':'Negro','White':'Blanco','Navy':'Azul marino','Blue':'Azul','Green':'Verde','Grey':'Gris','Gray':'Gris','Pink':'Rosa','Red':'Rojo','Purple':'Morado','Brown':'Marrón','Gold':'Dorado','Silver':'Plateado','Rose':'Rosa','Lavender':'Lavanda','Plum':'Ciruela','Espresso':'Café','Raspberry':'Frambuesa','Mahogany':'Caoba','Pearl':'Perla','Beach':'Playa','Ball':'Balón','Floral':'Floral','Multi':'Multicolor','Meadow':'Pradera','Rainforest':'Selva','Faint':'Lavanda claro','Brilliant':'Brillante','Oxford':'Oxford','Tide':'Marea'};
  const lookupColour=x=>{const key=Object.keys(colourWords).find(k=>k.toLowerCase()===x.toLowerCase());return key?colourWords[key]:x};
  const colourName=n=>{const raw=String(n||'');const direct=Object.keys(colourEs).find(k=>k.toLowerCase()===raw.toLowerCase());return direct?colourEs[direct]:raw.split(/([/ -])/).map(lookupColour).join('')};
  const legalEs={about:['SOBRE VEROLAFIT','Creamos ropa deportiva moldeadora que celebra la fuerza en todas sus formas. Nuestra misión es que cada mujer se sienta increíble.'],contact:['CONTACTO','¿Necesitas ayuda? Escríbenos a support@example.com. Atención de lunes a viernes, de 9:00 a 17:00.'],faq:['CENTRO DE AYUDA','Encuentra respuestas sobre pedidos, tallas, entrega gratuita en 48 horas, devoluciones durante 60 días, pagos y cuidado del producto.'],shipping:['ENVÍO GRATIS EN 48 HORAS','Todos los pedidos incluyen entrega gratuita en 48 horas. Recibirás el seguimiento por correo electrónico cuando el paquete salga de nuestro almacén.'],returns:['DEVOLUCIONES GRATIS Y GARANTÍA DE 60 DÍAS','Prueba cualquier producto durante 60 días. Si no es perfecto para ti, devuélvelo gratuitamente y recibirás el reembolso, sin preguntas.'],reviews:['MÁS DE 5.000 CLIENTES FELICES','Nuestra comunidad valora el corte favorecedor, los tejidos suaves y la comodidad de Verolafit.'],terms:['TÉRMINOS Y CONDICIONES','Estos términos regulan el uso de la tienda y los pedidos. Todos los productos incluyen envío gratis en 48 horas y garantía de devolución de 60 días. Se respetan los derechos obligatorios de los consumidores en España y la Unión Europea.'],privacy:['PRIVACIDAD Y PAGO SEGURO','Utilizamos tecnología cifrada para proteger los pagos. Solo recopilamos los datos necesarios para procesar pedidos, prestar el servicio y mejorar tu experiencia. Puedes solicitar acceso, rectificación o supresión de tus datos.'],cookies:['POLÍTICA DE COOKIES','Este sitio utiliza cookies esenciales para la cesta y, con tu consentimiento, cookies analíticas. Puedes gestionar tus preferencias desde el navegador.'],legal:['AVISO LEGAL','Importante: la razón social, NIF/CIF, domicilio registrado, datos mercantiles y contacto son campos provisionales que deben sustituirse por los datos legales verificados del vendedor antes de publicar la tienda.'],loyalty:['RECOMPENSAS VEROLAFIT','Únete a más de 5.000 clientes para recibir recompensas y acceso anticipado.'],"size-guide":['GUÍA DE TALLAS','Consulta las equivalencias XS–XXL y tus medidas corporales. Todos los productos incluyen devolución gratuita durante 60 días.']};
  const baseHome=home,baseCollection=collection,baseProductPage=productPage,baseCheckout=checkout,baseNotFound=notFound,baseBindPage=bindPage,baseRenderCart=renderCart;
  home=()=>translateHtml(baseHome());collection=slug=>translateHtml(baseCollection(slug));productPage=handle=>translateHtml(baseProductPage(handle));notFound=()=>translateHtml(baseNotFound());
  page=name=>{const v=legalEs[name]||['PÁGINA','Contenido próximamente.'];return `<article class="legal"><h1>${v[0]}</h1><p>${v[1]}</p><h2>Información importante</h2><p>Esta página está redactada en español para la tienda Verolafit. Contacta con atención al cliente si necesitas esta información en un formato accesible.</p></article>`};
  checkout=()=>`<div class="checkout"><h1>FINALIZAR COMPRA</h1><div class="checkout-grid"><form id="checkoutForm"><h2>Contacto</h2><input required type="email" placeholder="Correo electrónico"><h2>Dirección de entrega</h2><input required placeholder="Nombre"><input required placeholder="Apellidos"><input required placeholder="Dirección"><input required placeholder="Ciudad"><input required placeholder="Código postal"><select><option>España</option></select><h2>Pago</h2><p>Esta es una demostración de la tienda. No se realizará ningún cobro real.</p><button class="atc">COMPLETAR PEDIDO DE PRUEBA</button></form><div><h2>Tu pedido</h2>${cart.map(x=>`<div class="cart-line"><img src="${x.image}"><div><b>${esc(x.title)}</b><br><small>${esc(x.variant||'')}</small></div><b>${euroMoney(x.price)}</b></div>`).join('')}<h2>Total ${euroMoney(cart.reduce((s,x)=>s+x.price,0))}</h2></div></div></div>`;
  const letterSizes=['XS','S','M','L','XL','XXL'];
  const buttons=(cls,kind='')=>letterSizes.map((s,i)=>`<button class="choice ${cls} ${i===1?'active':''}" ${kind?`data-kind="${kind}"`:''} data-size="${s}" data-value="${s}">${s}</button>`).join('');
  const bindLetterGroup=(selector)=>document.querySelectorAll(selector).forEach(b=>b.onclick=()=>{document.querySelectorAll(selector).forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  function localizeSizes(){
    document.querySelectorAll('.details .choices').forEach(group=>{if(group.classList.contains('lulu-sizes')||group.classList.contains('air-top-sizes')||group.classList.contains('air-bottom-sizes'))return;if(!group.dataset.es){group.dataset.es='1';group.innerHTML=buttons('es-generic-size');bindLetterGroup('.es-generic-size')}});
    if(location.hash.endsWith('define-jacket-nulu')){const group=$('.lulu-sizes');if(group){group.innerHTML=buttons('lulu-size');bindLetterGroup('.lulu-size')}document.querySelectorAll('.model-choice,.lulu-product .colour-swatch').forEach(b=>{if(!b.dataset.esRelocalize){b.dataset.esRelocalize='1';b.addEventListener('click',()=>setTimeout(localizeSizes,0))}});document.querySelectorAll('.lulu-product .colour-swatch').forEach(b=>{b.title=colourName(b.dataset.colour);const img=b.querySelector('img');if(img)img.alt=colourName(b.dataset.colour)});const current=$('.lulu-current-colour');if(current)current.textContent=colourName($('.colour-swatch.active')?.dataset.colour||current.textContent);const guide=$('#sizeGuidePanel .size-table-wrap');if(guide)guide.innerHTML='<table><thead><tr><th>Talla</th><th>ES</th><th>Pecho</th><th>Cintura</th><th>Cadera</th></tr></thead><tbody><tr><td>XS</td><td>34</td><td>80–84</td><td>62–66</td><td>86–90</td></tr><tr><td>S</td><td>36</td><td>84–88</td><td>66–70</td><td>90–94</td></tr><tr><td>M</td><td>38</td><td>88–92</td><td>70–74</td><td>94–98</td></tr><tr><td>L</td><td>40</td><td>92–98</td><td>74–80</td><td>98–104</td></tr><tr><td>XL</td><td>42</td><td>98–104</td><td>80–86</td><td>104–110</td></tr><tr><td>XXL</td><td>44–46</td><td>104–112</td><td>86–94</td><td>110–118</td></tr></tbody></table><p><b>Cómo medirte:</b> mide el contorno de pecho y cadera por la zona más ancha y la cintura por la parte más estrecha.</p>';const atc=$('#addToCart'),p=products.find(x=>x.handle==='define-jacket-nulu');if(atc)atc.onclick=()=>{const model=$('.model-choice.active')?.dataset.model||'Full Length',colour=$('.colour-swatch.active')?.dataset.colour,size=$('.lulu-size.active')?.dataset.size||'S',v=p.variants.find(x=>x.options[0].value===model&&x.options[1].value===colour)||p.variants[0];cart.push({handle:p.handle,title:model==='Cropped'?'Define Cropped Jacket Nulu':'Define Jacket Nulu',price:v.price,image:v.image,variant:`${model==='Cropped'?'Corto':'Largo'} · ${colourName(colour)} · ${size}`});saveCart();toast('Añadido a tu bolsa')}}
    if(location.hash.endsWith('airbrush-set')){const top=$('.air-top-sizes'),bottom=$('.air-bottom-sizes');if(top){top.innerHTML=buttons('air-size','top');bottom.innerHTML=buttons('air-size','bottom');bindLetterGroup('.air-size[data-kind="top"]');bindLetterGroup('.air-size[data-kind="bottom"]')}document.querySelectorAll('.air-colours .colour-swatch').forEach(b=>{b.title=colourName(b.dataset.colour);const img=b.querySelector('img');if(img)img.alt=colourName(b.dataset.colour)});const current=$('.air-colour-name');if(current)current.textContent=colourName($('.air-colours .active')?.dataset.colour||current.textContent);const guide=$('#airSizePanel .size-table-wrap');if(guide)guide.innerHTML='<h3>SUJETADOR DEPORTIVO</h3><table><thead><tr><th>Talla</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>Contorno</th><td>30</td><td>32</td><td>34</td><td>36</td><td>38</td><td>40</td></tr></tbody></table><h3>PARTE INFERIOR</h3><table><thead><tr><th>Talla</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>ES</th><td>34</td><td>36</td><td>38</td><td>40</td><td>42</td><td>44–46</td></tr></tbody></table><p>Puedes elegir tallas diferentes para la parte superior e inferior.</p>';const atc=$('#addToCart'),p=products.find(x=>x.handle==='airbrush-set');if(atc)atc.onclick=()=>{const colour=$('.air-colours .active')?.dataset.colour,topSize=$('.air-top-sizes .active')?.dataset.size||'S',bottomSize=$('.air-bottom-sizes .active')?.dataset.size||'S',img=$('.air-colours .active')?.dataset.image;cart.push({handle:p.handle,title:p.title,price:25,image:img,variant:`${colourName(colour)} · Arriba ${topSize} · Abajo ${bottomSize} · Tote Alo Yoga gratis`});saveCart();toast('Conjunto completo y tote gratis añadidos')}}
    document.querySelectorAll('.video-card source').forEach(s=>{const raw=s.getAttribute('src');if(raw?.startsWith('assets/')){s.setAttribute('src','../'+raw);s.parentElement.load()}});translateDom(document.querySelector('main'));
  }
  renderCart=function(){baseRenderCart();translateDom($('.cart-panel'))};
  bindPage=function(){baseBindPage();localizeSizes();translateDom();document.querySelectorAll('.video-stories small').forEach(x=>{if(x.textContent==='VEROLAFIT COMMUNITY')x.textContent='COMUNIDAD VEROLAFIT';if(x.textContent==='ALO COMMUNITY')x.textContent='COMUNIDAD ALO'})};
  renderCart();
  render();
})();
