(function(){
  const replacements=[
    ['Unisex Half-Crew Throwback Sock','Unisex Half-Crew Throwback sokken'],['20 colours','20 kleuren'],['BUILT FOR STRENGTH','GEMAAKT VOOR KRACHT'],['Made for every shake and hold — movement that feels like you.','Gemaakt voor elke beweging — sportkleding waarin jij je goed voelt.'],['SHOP NOW','SHOP NU'],
    ['NEW RELEASES','NIEUWE ITEMS'],['Explore our latest products','Ontdek onze nieuwste producten'],['Shop all','Bekijk alles'],['OWN YOUR JOURNEY','VOLG JOUW EIGEN PAD'],['Stories of Strength Capsule','Stories of Strength-collectie'],['BUILD YOUR WISHLIST','MAAK JE VERLANGLIJST'],
    ['BEST SELLERS','BESTSELLERS'],['Your favourites, right here','Jouw favorieten op één plek'],['SHOP BY CATEGORY','SHOP PER CATEGORIE'],['Find your movement essential','Vind jouw onmisbare sportitems'],['JUST FOR YOU','SPECIAAL VOOR JOU'],['Our top recommendations','Onze beste aanbevelingen'],
    ['products','producten'],['Search this collection','Zoek in deze collectie'],['Featured','Uitgelicht'],['Price: low to high','Prijs: laag naar hoog'],['Price: high to low','Prijs: hoog naar laag'],['All categories','Alle categorieën'],
    ['In stock — ready to ship','Op voorraad — klaar voor verzending'],['In stock — all sizes available','Op voorraad — alle maten beschikbaar'],['SELECT FIT','KIES HET MODEL'],['SELECT COLOUR','KIES DE KLEUR'],['SELECT US SIZE (UK SIZE)','KIES JE MAAT'],['UK SIZE GUIDE','EU MAATTABEL'],
    ['ADD TO BAG','IN WINKELMAND'],['ADD THE COMPLETE SET TO BAG','VOEG DE COMPLETE SET TOE'],['5,000+ happy customers','Meer dan 5.000 tevreden klanten'],['Read reviews','Lees reviews'],['Read Airbrush Set reviews','Lees Airbrush Set-reviews'],
    ['FREE 48H SHIPPING','GRATIS VERZENDING BINNEN 48 UUR'],['On every UK order','Voor elke Nederlandse bestelling'],['60-DAY RETURNS','60 DAGEN RETOURNEREN'],['Free, no questions asked','Gratis, zonder vragen'],['SECURE PAYMENT','VEILIG BETALEN'],['SSL encrypted checkout','SSL-beveiligde betaling'],
    ['YOUR COMPLIMENTARY GIFT','JOUW GRATIS CADEAU'],['SPORTS BRA','SPORTBEHA'],['BOTTOM','BROEK'],['Select the top and bottom independently','Kies de maat van de top en broek apart'],['Body measurements in centimetres','Lichaamsmaten in centimeters'],['Bust','Borst'],['Waist','Taille'],['Hip','Heup'],['How to measure:','Zo meet je:'],
    ['FREE GIFT WITH YOUR SET','GRATIS CADEAU BIJ JE SET'],['Automatically included in your parcel — no code needed.','Automatisch aan je pakket toegevoegd — geen code nodig.'],['FREE','GRATIS'],['COMPLETE 2-PIECE SET','COMPLETE 2-DELIGE SET'],['Sports bra + matching bottom','Sportbeha + bijpassende broek'],['1. CHOOSE YOUR TOP SIZE','1. KIES DE MAAT VAN JE TOP'],['2. CHOOSE YOUR BOTTOM SIZE','2. KIES DE MAAT VAN JE BROEK'],
    ['Excellent','Uitstekend'],['Based on 649 product reviews','Gebaseerd op 649 productreviews'],['Loved by 5,000+ customers','Geliefd bij meer dan 5.000 klanten'],['Verified customer','Geverifieerde klant'],['out of 5','van 5'],['Based on 5,127 customer reviews','Gebaseerd op 5.127 klantreviews'],['Close reviews','Reviews sluiten'],['Customer reviews','Klantreviews'],['Airbrush Set reviews','Airbrush Set-reviews'],
    ['The best matching set','De beste bijpassende set'],['Looks expensive','Ziet er luxe uit'],['Immediately ordered another colour','Meteen een andere kleur besteld'],['The fabric is smooth, supportive and so flattering. I love that I could choose a different size for my bra and leggings.','De stof is zacht, ondersteunend en zeer flatterend. Fijn dat ik voor de beha en legging een andere maat kon kiezen.'],['The Airbrush set fits beautifully and stays in place through my full workout. The free tote is such a nice bonus.','De Airbrush Set zit prachtig en blijft tijdens mijn hele workout op zijn plaats. De gratis tas is een mooie bonus.'],['Soft, sculpting and completely squat proof. For £26, this two-piece set is incredible.','Zacht, vormgevend en volledig squatproof. Voor €29,95 is deze tweedelige set geweldig.'],
    ['Soft, sculpting and flattering','Zacht, vormgevend en flatterend'],['The fabric is super soft and both jacket lengths give a beautiful sculpted silhouette.','De stof is superzacht en beide lengtes creëren een prachtig vormgegeven silhouet.'],['I love having both fits','Ik vind beide modellen geweldig'],['The cropped fit is perfect with high-rise leggings while the full length is my everyday favourite.','Het korte model past perfect bij een high-waist legging en het lange model is mijn dagelijkse favoriet.'],['Amazing jacket family','Een geweldige jassencollectie'],['The close fit is flattering and the Nulu fabric stays soft enough for all-day wear.','De aansluitende pasvorm flatteert en de zachte Nulu-stof blijft de hele dag comfortabel.'],['It gives me the same polished look I love in my Lululemon Define Jacket, but feels lighter for everyday wear.','Het geeft dezelfde verzorgde look als mijn Lululemon Define Jacket, maar voelt lichter voor dagelijks gebruik.'],['The waist is so flattering and the stretch is perfect. I have worn it for Pilates, errands and travel.','De taille is erg flatterend en de stretch is perfect. Ik draag hem voor pilates, boodschappen en op reis.'],
    ['The perfect Define Jacket alternative','Het perfecte alternatief voor de Define Jacket'],['Flattering and true to size','Flatterend en valt op maat'],['My new everyday layer','Mijn nieuwe favoriet voor elke dag'],['Beautiful sculpted fit and incredibly soft fabric.','Prachtig vormgevend model en ongelooflijk zachte stof.'],['Premium finish, smooth zip and a close fit without feeling restrictive.','Premium afwerking, soepele rits en een aangesloten pasvorm zonder te knellen.'],['I immediately ordered another colour.','Ik heb meteen een andere kleur besteld.'],
    ['Choose your fit','Kies je model'],['Fit and features','Pasvorm en kenmerken'],['Free 48-hour shipping','Gratis verzending binnen 48 uur'],['Free 60-day returns','60 dagen gratis retourneren'],['60-day guarantee','60 dagen garantie'],['Product details','Productdetails'],['What is included?','Wat is inbegrepen?'],['Fit & fabric','Pasvorm en stof'],['YOU MAY ALSO LIKE','MISSCHIEN VIND JE DIT OOK LEUK'],['Complete the look','Maak je look compleet'],['COMPLETE THE LOOK','MAAK DE LOOK COMPLEET'],['More movement essentials','Meer sportfavorieten'],
    ['Everyday sculpt','Elke dag vormgevend'],['Made to move','Gemaakt om te bewegen'],['Your strongest self','Jouw sterkste zelf'],['Confidence in motion','Zelfvertrouwen in beweging'],['Play video','Video afspelen'],['Previous videos','Vorige video’s'],['Next videos','Volgende video’s'],['Swipe to explore','Swipe om te ontdekken'],['MOVE WITH US','BEWEEG MET ONS MEE'],['Real movement. Real confidence.','Echte beweging. Echt zelfvertrouwen.'],['AIRBRUSH IN MOTION','AIRBRUSH IN BEWEGING'],['The set, styled your way.','De set, gestyled op jouw manier.'],
    ['One Airbrush sports bra, one matching Airbrush bottom and one complimentary Alo Yoga tote bag.','Eén Airbrush sportbeha, één bijpassende Airbrush broek en één gratis Alo Yoga-tas.'],['Sculpting, smoothing performance fabric with comfortable four-way stretch. Choose the top and bottom sizes separately.','Vormgevende, gladmakende sportstof met comfortabele vierwegstretch. Kies de maten van de top en broek apart.'],['Choose your usual size for a sculpted fit. Because this is a set, your sports bra and bottom sizes can be different.','Kies je gebruikelijke maat voor een vormgevende pasvorm. Voor de sportbeha en broek kun je verschillende maten kiezen.'],['Soft Nulu™ fabric, zippered pockets, thumbholes and Cuffins™, locker loop, zipper garage and an elastic hair-tie zipper pull.','Zachte Nulu™-stof, zakken met rits, duimgaten, comfortabele manchetten, ophanglus en een elastisch ritskoord.'],['Try your complete set at home for 60 days. Returns are free and refunded with no questions asked.','Probeer de complete set 60 dagen thuis. Retourneren is gratis en je krijgt zonder vragen je geld terug.'],
    ['Free 48-hour shipping','Gratis verzending binnen 48 uur'],['Every UK order qualifies for free delivery, dispatched for arrival within 48 hours.','Elke Nederlandse bestelling wordt gratis verzonden en binnen 48 uur bezorgd.'],['Free 60-day returns','60 dagen gratis retourneren'],['Try it at home for 60 days. Returns are free and refunded with no questions asked.','Probeer het 60 dagen thuis. Retourneren is gratis en je krijgt zonder vragen je geld terug.'],
    ['YOUR SHOPPING BAG','JE WINKELMAND'],['Your shopping bag is empty.','Je winkelmand is leeg.'],['Remove','Verwijderen'],['Subtotal','Subtotaal'],['CHECKOUT','AFREKENEN'],['Added to your bag','Toegevoegd aan je winkelmand'],['Please select an available size','Kies een beschikbare maat'],['PAGE NOT FOUND','PAGINA NIET GEVONDEN'],['That page moved faster than we did.','Deze pagina is niet meer beschikbaar.'],['BACK HOME','TERUG NAAR HOME']
  ];
  const euroValue=value=>{const n=Number(value)||0;return n===9?9.99:n===26?29.95:n===25?29.95:n===17?19.99:Math.round(n*1.16)};
  const euroMoney=value=>`${euroValue(value).toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})} €`;
  const convertPounds=html=>String(html).replace(/£\s*([\d,]+(?:\.\d+)?)/g,(_,raw)=>euroMoney(Number(raw.replace(/,/g,''))));
  const translateHtml=html=>convertPounds(replacements.reduce((s,[a,b])=>s.split(a).join(b),html));
  const exactNl={'NEW':'NIEUW','SALE':'SALE','SHORTS':'SHORTS','BRAS':"SPORTBEHA'S",'LEGGINGS':'LEGGINGS','TOPS':'TOPS','PANTS':'BROEKEN','HOODIES':'HOODIES','ACCESSORIES':'ACCESSOIRES','DRESSES':'JURKEN','Full Length':'Lang model','Cropped':'Kort model','Two fits · multiple colours':'Twee modellen · meerdere kleuren','7 colours':'7 kleuren'};
  const colourNl={'Black':'Zwart','White':'Wit','Navy':'Marineblauw','Grey':'Grijs','Gray':'Grijs','Pink':'Roze','Red':'Rood','Blue':'Blauw','Green':'Groen','Brown':'Bruin','Beige':'Beige','Purple':'Paars','Orange':'Oranje','Yellow':'Geel','Anthracite / White':'Antraciet / Wit','Black / White':'Zwart / Wit','Navy / White':'Marineblauw / Wit','White / Black':'Wit / Zwart','Grass':'Grasgroen','California Blue':'Californiëblauw'};
  const colourName=n=>{const raw=String(n||'');const direct=Object.keys(colourNl).find(k=>k.toLowerCase()===raw.toLowerCase());return direct?colourNl[direct]:raw.replace(/Black/gi,'Zwart').replace(/White/gi,'Wit').replace(/Blue/gi,'Blauw').replace(/Green/gi,'Groen').replace(/Grey|Gray/gi,'Grijs').replace(/Pink/gi,'Roze').replace(/Red/gi,'Rood').replace(/Brown/gi,'Bruin').replace(/Purple/gi,'Paars')};
  const translateDom=(root=document.body)=>{if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.parentElement?.closest('script,style'))return;const raw=n.nodeValue,trim=raw.trim();if(!trim)return;const translated=exactNl[trim]||colourNl[trim]||translateHtml(trim);n.nodeValue=raw.replace(trim,translated)})};
  const legalNl={about:['OVER VEROLAFIT','Wij maken vormgevende sportkleding die kracht in elke vorm viert. Onze missie is dat iedere vrouw zich geweldig voelt.'],contact:['CONTACT','Hulp nodig? Mail naar support@example.com. Onze klantenservice is bereikbaar van maandag tot en met vrijdag, van 9.00 tot 17.00 uur.'],faq:['HELPCENTRUM','Vind antwoorden over bestellingen, maten, gratis bezorging binnen 48 uur, 60 dagen retourneren, betalingen en productverzorging.'],shipping:['GRATIS VERZENDING BINNEN 48 UUR','Alle bestellingen in Nederland worden gratis binnen 48 uur bezorgd. Zodra je pakket ons magazijn verlaat, ontvang je de track-en-trace per e-mail.'],returns:['60 DAGEN GRATIS RETOURNEREN EN GARANTIE','Probeer ieder product 60 dagen thuis. Niet helemaal tevreden? Retourneer het gratis en ontvang zonder vragen je geld terug.'],reviews:['MEER DAN 5.000 TEVREDEN KLANTEN','Onze community waardeert de flatterende pasvorm, zachte stoffen en het dagelijkse comfort van Verolafit.'],terms:['ALGEMENE VOORWAARDEN','Deze voorwaarden zijn van toepassing op het gebruik van de winkel en alle bestellingen. Alle producten hebben gratis verzending binnen 48 uur en 60 dagen retourgarantie. De verplichte consumentenrechten in Nederland en de Europese Unie blijven volledig van toepassing.'],privacy:['PRIVACY EN VEILIG BETALEN','Wij gebruiken versleutelde technologie om betalingen te beveiligen. We verzamelen alleen gegevens die nodig zijn voor je bestelling, onze dienstverlening en het verbeteren van je ervaring. Je kunt inzage, correctie of verwijdering van je gegevens aanvragen.'],cookies:['COOKIEBELEID','Deze site gebruikt noodzakelijke cookies voor de winkelmand en, met jouw toestemming, analytische cookies. Je kunt je voorkeuren beheren via je browser.'],legal:['WETTELIJKE INFORMATIE','Belangrijk: bedrijfsnaam, KvK-nummer, btw-nummer, vestigingsadres en contactgegevens zijn tijdelijke velden en moeten vóór publicatie worden vervangen door de geverifieerde juridische gegevens van de verkoper.'],loyalty:['VEROLAFIT REWARDS','Sluit je aan bij meer dan 5.000 klanten voor beloningen en vroege toegang.'],'size-guide':['EU MAATTABEL','Bekijk de Europese maatvoering van XS tot XXL en de bijbehorende lichaamsmaten. Alle producten kunnen 60 dagen gratis worden geretourneerd.']};
  const baseHome=home,baseCollection=collection,baseProductPage=productPage,baseNotFound=notFound,baseBindPage=bindPage,baseRenderCart=renderCart;
  home=()=>translateHtml(baseHome());collection=slug=>translateHtml(baseCollection(slug));productPage=handle=>translateHtml(baseProductPage(handle));notFound=()=>translateHtml(baseNotFound());
  page=name=>{const v=legalNl[name]||['PAGINA','Inhoud volgt binnenkort.'];return `<article class="legal"><h1>${v[0]}</h1><p>${v[1]}</p><h2>Belangrijke informatie</h2><p>Deze pagina is in het Nederlands opgesteld voor de Nederlandse Verolafit-winkel. Neem contact op met onze klantenservice als je deze informatie in een toegankelijk formaat nodig hebt.</p></article>`};
  checkout=()=>`<div class="checkout"><h1>AFREKENEN</h1><div class="checkout-grid"><form id="checkoutForm"><h2>Contact</h2><input required type="email" placeholder="E-mailadres"><h2>Bezorgadres</h2><input required placeholder="Voornaam"><input required placeholder="Achternaam"><input required placeholder="Adres"><input required placeholder="Plaats"><input required placeholder="Postcode"><select><option>Nederland</option></select><h2>Betaling</h2><p>Dit is een demonstratiewinkel. Er wordt geen echte betaling uitgevoerd.</p><button class="atc">DEMO-BESTELLING AFRONDEN</button></form><div><h2>Je bestelling</h2>${cart.map(x=>`<div class="cart-line"><img src="${x.image}"><div><b>${esc(x.title)}</b><br><small>${esc(x.variant||'')}</small></div><b>${euroMoney(x.price)}</b></div>`).join('')}<h2>Totaal ${euroMoney(cart.reduce((s,x)=>s+x.price,0))}</h2></div></div></div>`;
  const sizes=['XS','S','M','L','XL','XXL'];
  const sizeButtons=(classes,kind='')=>sizes.map((s,i)=>`<button class="choice ${classes} ${i===1?'active':''}" ${kind?`data-kind="${kind}"`:''} data-size="${s}" data-value="${s}">${s}</button>`).join('');
  const bindGroup=selector=>document.querySelectorAll(selector).forEach(b=>b.onclick=()=>{document.querySelectorAll(selector).forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  function localizeProduct(){
    if(location.hash.endsWith('define-jacket-nulu')){const group=$('.lulu-sizes');if(group){group.innerHTML=sizeButtons('lulu-size');bindGroup('.lulu-size')}document.querySelectorAll('.model-choice,.lulu-product .colour-swatch').forEach(b=>{if(!b.dataset.nlRelocalize){b.dataset.nlRelocalize='1';b.addEventListener('click',()=>setTimeout(localizeProduct,0))}});document.querySelectorAll('.lulu-product .colour-swatch').forEach(b=>b.title=colourName(b.dataset.colour));const current=$('.lulu-current-colour');if(current)current.textContent=colourName($('.colour-swatch.active')?.dataset.colour||current.textContent);const currentModel=$('.lulu-current-model'),model=$('.model-choice.active')?.dataset.model;if(currentModel&&model)currentModel.textContent=model==='Cropped'?'Kort model':'Lang model';const guide=$('#sizeGuidePanel .size-table-wrap');if(guide)guide.innerHTML='<table><thead><tr><th>Maat</th><th>EU</th><th>Borst</th><th>Taille</th><th>Heup</th></tr></thead><tbody><tr><td>XS</td><td>34</td><td>80–84</td><td>62–66</td><td>86–90</td></tr><tr><td>S</td><td>36</td><td>84–88</td><td>66–70</td><td>90–94</td></tr><tr><td>M</td><td>38</td><td>88–92</td><td>70–74</td><td>94–98</td></tr><tr><td>L</td><td>40</td><td>92–98</td><td>74–80</td><td>98–104</td></tr><tr><td>XL</td><td>42</td><td>98–104</td><td>80–86</td><td>104–110</td></tr><tr><td>XXL</td><td>44–46</td><td>104–112</td><td>86–94</td><td>110–118</td></tr></tbody></table><p><b>Zo meet je:</b> meet borst en heup op het breedste punt en je taille op het smalste punt. Afmetingen in cm.</p>';}
    if(location.hash.endsWith('airbrush-set')){const top=$('.air-top-sizes'),bottom=$('.air-bottom-sizes');if(top&&bottom){top.innerHTML=sizeButtons('air-size','top');bottom.innerHTML=sizeButtons('air-size','bottom');bindGroup('.air-size[data-kind="top"]');bindGroup('.air-size[data-kind="bottom"]')}document.querySelectorAll('.air-colours .colour-swatch').forEach(b=>{b.title=colourName(b.dataset.colour);if(!b.dataset.nlRelocalize){b.dataset.nlRelocalize='1';b.addEventListener('click',()=>setTimeout(localizeProduct,0))}});const current=$('.air-colour-name');if(current)current.textContent=colourName($('.air-colours .active')?.dataset.colour||current.textContent);const guide=$('#airSizePanel .size-table-wrap');if(guide)guide.innerHTML='<h3>SPORTBEHA</h3><table><thead><tr><th>Maat</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>EU omvang</th><td>65</td><td>70</td><td>75</td><td>80</td><td>85</td><td>90</td></tr></tbody></table><h3>BROEK</h3><table><thead><tr><th>Maat</th><th>XS</th><th>S</th><th>M</th><th>L</th><th>XL</th><th>XXL</th></tr></thead><tbody><tr><th>EU</th><td>34</td><td>36</td><td>38</td><td>40</td><td>42</td><td>44–46</td></tr></tbody></table><p>Je kunt voor de top en broek verschillende maten kiezen.</p>';}
    translateDom(document.querySelector('main'));
  }
  renderCart=function(){baseRenderCart();translateDom($('.cart-panel'))};
  bindPage=function(){baseBindPage();localizeProduct();document.querySelectorAll('.video-stories small').forEach(x=>{if(x.textContent==='VEROLAFIT COMMUNITY')x.textContent='VEROLAFIT COMMUNITY';if(x.textContent==='ALO COMMUNITY')x.textContent='ALO COMMUNITY'});$('#searchBtn').onclick=()=>{const q=prompt('Producten zoeken');if(q)location.hash='/collection/'+encodeURIComponent(q)};const form=$('#checkoutForm');if(form)form.onsubmit=e=>{e.preventDefault();cart=[];saveCart();e.target.innerHTML='<h2>BEDANKT</h2><p>Je demo-bestelling is ontvangen.</p><a class="btn" href="#/">VERDER WINKELEN</a>'};if(location.hash.endsWith('define-jacket-nulu')){const p=products.find(x=>x.handle==='define-jacket-nulu');$('#addToCart').onclick=()=>{const model=$('.model-choice.active')?.dataset.model,colour=$('.colour-swatch.active')?.dataset.colour,size=$('.lulu-size.active')?.dataset.size;if(!model||!colour||!size)return toast('Kies het model, de kleur en de maat');const variant=p.variants.find(x=>x.options[0].value===model&&x.options[1].value===colour&&x.available);if(!variant)return toast('Kies een beschikbare variant');location.href=buildMolipyUrl('https://www.molipy8trk.com/938L6R/PHK1H6Q/','DEFINE',[{productName:model==='Cropped'?'Define Cropped Jacket Nulu':'Define Jacket Nulu',model:colour,size,imageUrl:variant.image},{productName:'Lululemon Sport Bottle 24oz Straw Lid',model:'Gratis cadeau',imageUrl:'https://images.lululemon.com/is/image/lululemon/LU9BA8S_0002_1?size=1200,1200'}])}}if(location.hash.endsWith('airbrush-set')){const p=products.find(x=>x.handle==='airbrush-set');$('#addToCart').onclick=()=>{const colour=$('.air-colours .active')?.dataset.colour,top=$('.air-top-sizes .active')?.dataset.size,bottom=$('.air-bottom-sizes .active')?.dataset.size,img=$('.air-colours .active')?.dataset.image;if(!colour||!top||!bottom||!img)return toast('Kies de kleur en beide maten');location.href=buildMolipyUrl('https://www.molipy8trk.com/938L6R/PGWZ1LT/Global','AIRBRUSH',[{productName:'Airbrush Sports Bra',color:colour,size:top,imageUrl:img},{productName:'Airbrush Bottom',color:colour,size:bottom,imageUrl:img},{productName:'Alo Yoga Tote Bag',model:'Gratis cadeau',imageUrl:p.gift.image}])}}};
  renderCart();render();
})();
